### ISSUE TITLE
The translation of the header buttons does not work

### ISSUE THREAD

**Issue by aurormss** [ptc-iot-sharing/CalendarWidgetTWX#10]
Hello,

I wanted to test the translation of the widget on Thingworx, and I realized that it doesn't work on the header buttons: today, month, week, day... and the text field that marks the number of the week when you are in week view. Also, the 1st day of the week does not change (Sunday -> Monday)

![image](https://user-images.githubusercontent.com/47112841/118991235-d6c4ad00-b983-11eb-9d65-36589da1162a.png)

I can't find out where the problem comes from, is it in the dependencies download or in the widget building ?

I hope you have the solution. Thank you in advance for your help.

**Comment by BogdanMihaiciuc** [comment]
Hey, the widget itself doesn't really handle localization. Instead, the underlying `fullcalendar` library handles this and support should include localizing the header buttons.

For more information on what it supports, you can check out its official documentation here:
[https://fullcalendar.io/docs/v4/locale](https://fullcalendar.io/docs/v4/locale)

One thing you can try, is to set the locale value both statically and via a binding to see if this is an issue related to either initialization or updating.

**Comment by aletenti** [comment]
Hello Bogdan,
I'm using version 1.3.3 and I'm facing the same issue.
I have tried to unbind the dynamic "locale" value and set it statically and it works (I can see both headers and days in local language), but when I bind it dynamically I can not see the headers in local language.
I have also tried to update version to 2.0.0, but the headers disappeared (I mean the possibility to change the Calendar view).

Do you know why only headers are not translated in version 1.3.3 when the "locale" property is bound dynamically?

Thanks in advance,
Alessio

**Comment by BogdanMihaiciuc** [comment]
I'll need to look into it, but most likely it's an issue in `fullcalendar` since the widget itself doesn't do anything specific on its own with the localization field.

**Comment by BogdanMihaiciuc** [comment]
This should be fixed in [release 2.0.1](https://github.com/ptc-iot-sharing/CalendarWidgetTWX/releases/tag/2.0.1).

If the bug still isn't fixed, please reopen this issue.
